name: format and compilation test
on: 
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]

jobs:
  tests:
    name: Evaluate on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      # Don't cancel other OS runners if one fails.
      fail-fast: false
      matrix:
        # Put the operating systems you want to run on here.
        os: [ubuntu-latest, windows-latest, macos-latest]
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
      # Smaller cache size
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    defaults:
      run:
        # Use bash shells on all platforms.
        shell: bash
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        # Disable fetching history as most of the time it is useless
        # filter: tree:0
        # fetch-depth: 0
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        name: Setup .NET SDK
        with:
          # Use the .NET SDK from global.json in the root of the repository.
          global-json-file: global.json

      - name: Restore Dependencies
        run: dotnet restore

      - uses: chickensoft-games/setup-godot@v2
        name: Setup Godot
        with:
          # Version must include major, minor, and patch, and be >= 4.0.0
          # Pre-release label is optional.
          version: 4.5.1 # also valid: 4.0.0.rc1 or 4.0.0 or "global.json", etc
          # Use .NET-enabled version of Godot (the default is also true).
          use-dotnet: true
          # Include the Godot Export Templates (the default is false).
          include-templates: true

      - name: Verify Setup
        run: |
          dotnet --version
          godot --version

      - name: Generate .NET Bindings
        run: godot --headless --build-solutions --quit || exit 0

      - name: Build Projects
        run: dotnet build WZIMNIACY.sln --configuration ExportRelease

      - name: Check code format
        run: dotnet format style --verify-no-changes WZIMNIACY.sln --exclude Epic_EOS_SDK/**
